# Generated by Django 2.2.27 on 2024-01-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_log',
        ),
    ]
