# Generated by Django 2.2.27 on 2024-01-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20240117_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_message',
        ),
    ]
