# Generated by Django 2.2.27 on 2024-01-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20240117_1606'),
        ('chatbot', '0003_auto_20240120_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='bot_id',
        ),
        migrations.CreateModel(
            name='StudentBookBot',
            fields=[
                ('bot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='機器人ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Book', verbose_name='書籍')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '學生書籍機器人',
                'unique_together': {('student', 'book', 'bot_id')},
            },
        ),
    ]
