# Generated by Django 2.2.27 on 2024-01-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20240120_1756'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table=None,
        ),
    ]
