# Generated by Django 2.2.27 on 2024-01-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chatmessage_student_book_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='student_book_bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chatbot.StudentBookBot', verbose_name='學生書籍機器人'),
        ),
    ]
