# Generated by Django 2.2.27 on 2024-01-21 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20240120_1758'),
        ('chatbot', '0007_auto_20240120_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbookbot',
            name='bot_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='機器人ID'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbookbot',
            unique_together={('student', 'book')},
        ),
    ]
