# Generated by Django 2.2.27 on 2024-01-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=100)),
                ('chatroom_id', models.CharField(max_length=100)),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=4)),
                ('message', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('message_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '聊天訊息',
                'verbose_name_plural': '聊天訊息',
                'db_table': 'chat_message',
            },
        ),
    ]
