# Generated by Django 2.2.27 on 2024-01-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='書籍名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='書籍簡介')),
                ('content', models.TextField(blank=True, null=True, verbose_name='書籍內容')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='書籍作者')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='書籍出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='書籍出版日期')),
                ('category', models.CharField(blank=True, choices=[('fiction', '小說'), ('nonfiction', '非小說'), ('science', '科學'), ('history', '歷史')], max_length=100, null=True, verbose_name='書籍分類')),
                ('difficulty', models.CharField(blank=True, choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], max_length=50, null=True, verbose_name='書籍難度')),
            ],
            options={
                'verbose_name': '書籍',
                'verbose_name_plural': '書籍',
                'db_table': 'book',
                'ordering': ['book_id'],
            },
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='評分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.Book', verbose_name='書籍')),
            ],
            options={
                'verbose_name': '書籍評分',
                'verbose_name_plural': '書籍評分',
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
