# Generated by Django 2.2.27 on 2024-01-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20240117_1606'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
