# Generated by Django 2.2.27 on 2024-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20240128_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('小說', '小說'), ('非小說', '非小說'), ('科學', '科學'), ('歷史', '歷史'), ('故事', '故事'), ('人社', '人社'), ('其他', '其他')], max_length=100, null=True, verbose_name='書籍分類'),
        ),
        migrations.AlterField(
            model_name='book',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難'), ('繪本', '繪本'), ('橋梁書', '橋梁書'), ('初階文字書', '初階文字書'), ('中階文字書', '中階文字書'), ('高階文字書', '高階文字書')], max_length=50, null=True, verbose_name='書籍難度'),
        ),
    ]
