# Generated by Django 2.2.27 on 2024-01-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20240128_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='書籍分類'),
        ),
        migrations.AlterField(
            model_name='book',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='書籍難度'),
        ),
    ]
