# Generated by Django 2.2.3 on 2020-07-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='权限名')),
                ('method', models.CharField(choices=[('POST', '增'), ('DELETE', '删'), ('PUT', '改'), ('GET', '查')], max_length=50, verbose_name='方法')),
                ('path', models.CharField(max_length=200, verbose_name='请求路径正则')),
                ('desc', models.CharField(blank=True, default='', max_length=30, verbose_name='权限描述')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Permissions', verbose_name='父权限')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'permissions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='角色')),
                ('desc', models.CharField(blank=True, default='', max_length=50, verbose_name='描述')),
                ('permissions', models.ManyToManyField(blank=True, to='system.Permissions', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
    ]
