# Generated by Django 2.2.3 on 2020-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='权限描述'),
        ),
    ]
