# Generated by Django 2.2.13 on 2021-02-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='menu',
            field=models.BooleanField(verbose_name='是否为菜单'),
        ),
    ]
