# Generated by Django 2.2.13 on 2020-12-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='menu',
            field=models.CharField(choices=[(True, '菜单'), (False, '接口')], default='', max_length=8, verbose_name='是否为菜单'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissions',
            name='method',
            field=models.CharField(blank=True, choices=[('POST', '增'), ('DELETE', '删'), ('PUT', '改'), ('PATCH', '局部改'), ('GET', '查')], default='', max_length=8, verbose_name='方法'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='path',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='请求路径正则'),
        ),
    ]
