# Generated by Django 2.2.13 on 2021-01-17 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='资产管理员'),
        ),
        migrations.AddField(
            model_name='assets',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Cabinets', verbose_name='所在机柜'),
        ),
        migrations.AddField(
            model_name='assets',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Departments', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cmdb.Servers', verbose_name='服务器'),
        ),
    ]
