# Generated by Django 2.2.13 on 2020-10-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='address',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cmdb.Servers', verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='networkdevices',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='cmdb.Assets'),
        ),
        migrations.AlterField(
            model_name='securitydevices',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to='cmdb.Assets'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='cmdb.Assets'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='server_system_type',
            field=models.SmallIntegerField(choices=[(0, 'Unix'), (1, 'Linux'), (2, 'Windows'), (2, 'Netware')], default=0, verbose_name='服务器系统类型'),
        ),
        migrations.AlterField(
            model_name='storagedevices',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='cmdb.Assets'),
        ),
    ]
