# Generated by Django 2.2.13 on 2020-11-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20201021_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['id'], 'verbose_name': '服务器登录账户', 'verbose_name_plural': '服务器登录账户'},
        ),
        migrations.AlterField(
            model_name='networkdevices',
            name='device_type',
            field=models.SmallIntegerField(choices=[(0, '路由器'), (1, '交换机'), (2, '负载均衡'), (3, 'VPN设备')], default=0, verbose_name='网络设备类型'),
        ),
        migrations.AlterField(
            model_name='securitydevices',
            name='device_type',
            field=models.SmallIntegerField(choices=[(0, '防火墙'), (1, '入侵检测设备'), (2, '互联网网关'), (3, '运维审计系统')], default=0, verbose_name='安全设备类型'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='server_system_type',
            field=models.SmallIntegerField(choices=[(0, 'Unix'), (1, 'Linux'), (2, 'Windows'), (3, 'Netware')], default=0, verbose_name='服务器系统类型'),
        ),
        migrations.AlterField(
            model_name='storagedevices',
            name='device_type',
            field=models.SmallIntegerField(choices=[(0, '磁盘阵列'), (1, '网络存储器'), (2, '磁带库'), (3, '磁带机')], default=0, verbose_name='存储设备类型'),
        ),
    ]
