# Generated by Django 2.2.13 on 2020-10-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='用户')),
                ('view', models.CharField(max_length=32, verbose_name='视图')),
                ('desc', models.CharField(max_length=32, verbose_name='描述')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('detail', models.TextField(verbose_name='详情')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'monitor_error_log',
                'ordering': ['-id'],
            },
        ),
    ]
