# Generated by Django 2.2.13 on 2020-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20201003_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
            ],
            options={
                'verbose_name': 'IP黑名单',
                'verbose_name_plural': 'IP黑名单',
                'db_table': 'monitor_ipblacklist',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelTable(
            name='errorlogs',
            table='monitor_errorlogs',
        ),
    ]
