# Generated by Django 2.2.13 on 2020-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20201003_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlogs',
            options={'ordering': ['-id'], 'verbose_name': '错误日志', 'verbose_name_plural': '错误日志'},
        ),
        migrations.AlterField(
            model_name='ipblacklist',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP'),
        ),
    ]
