# Generated by Django 2.2.3 on 2020-07-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200729_2131'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Departments', verbose_name='部门'),
        ),
    ]
