# Generated by Django 2.2.13 on 2020-11-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20201003_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
