# Generated by Django 2.2.27 on 2024-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20240105_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='gender'),
        ),
    ]
