# Generated by Django 2.2.13 on 2020-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20201108_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
